# Task configurations for MeshAI CrewAI Backend
# These tasks support different types of agent interactions

initial_reaction_task:
  description: >
    Analyze the given topic or question: {topic}
    
    Provide your initial reaction from your unique perspective, covering:
    1. Your immediate impression and gut reaction
    2. Key points that align with your expertise and priorities
    3. Any concerns, opportunities, or insights you notice
    
    Keep your response authentic to your role and focused (2-3 sentences).
    Current context: {context}
  expected_output: >
    A brief, persona-specific reaction that reflects your unique perspective
    and expertise on the topic
  agent: {agent_name}

group_discussion_task:
  description: >
    Participate in a group discussion about: {topic}
    
    Other participants have shared these views:
    {other_reactions}
    
    Now contribute to the discussion by:
    1. Responding to what others have said (agree, disagree, or build upon)
    2. Adding your unique perspective or insights
    3. Asking relevant questions or raising new points
    
    Stay true to your persona and keep the conversation engaging.
    Discussion round: {round_number}
  expected_output: >
    A conversational response that engages with others' viewpoints while
    maintaining your authentic persona perspective
  agent: {agent_name}

focus_group_initial_task:
  description: >
    Analyze this marketing campaign/concept from your professional perspective:
    
    Campaign/Concept: {campaign_description}
    Session Goals: {session_goals}
    
    Provide your initial professional assessment covering:
    1. Immediate impression and overall reaction
    2. Key strengths and potential weaknesses you identify
    3. How this aligns with your area of expertise and concerns
    4. Specific recommendations or considerations from your viewpoint
    
    Be thorough but concise, focusing on actionable insights.
  expected_output: >
    A structured professional assessment with clear opinions, reasoning,
    and actionable insights from your expert perspective
  agent: {agent_name}

focus_group_discussion_task:
  description: >
    Continue the focus group discussion about: {campaign_description}
    
    Recent discussion points from other participants:
    {recent_context}
    
    Your role in this round ({round_number}) is to:
    1. Build on the discussion with your professional insights
    2. Address or respond to points raised by others
    3. Introduce new considerations from your expertise area
    4. Help the group reach deeper insights or identify key issues
    
    Maintain your professional perspective while being collaborative.
  expected_output: >
    A professional contribution that advances the discussion and provides
    valuable insights from your area of expertise
  agent: {agent_name}

campaign_analysis_task:
  description: >
    Conduct a comprehensive analysis of this marketing campaign:
    
    Campaign Details: {campaign_description}
    Target Goals: {analysis_goals}
    
    Provide a detailed analysis covering:
    1. Strategic positioning and target audience alignment
    2. Key messaging strengths and potential gaps
    3. Competitive advantages and challenges
    4. Implementation considerations and potential risks
    5. Recommendations for optimization
    
    Base your analysis on your professional expertise and industry knowledge.
  expected_output: >
    A comprehensive professional analysis report with strategic insights,
    actionable recommendations, and clear reasoning
  agent: {agent_name}

summary_synthesis_task:
  description: >
    Create an executive summary of the focus group discussion about: {topic}
    
    Discussion Context:
    {full_discussion_context}
    
    Synthesize the key findings into a comprehensive report including:
    1. Overview of main themes and insights that emerged
    2. Areas of consensus and disagreement among participants
    3. Critical concerns and opportunities identified
    4. Actionable recommendations based on the collective input
    5. Next steps or areas requiring further investigation
    
    Present findings in a clear, professional format suitable for stakeholders.
  expected_output: >
    A structured executive summary report that captures key insights,
    consensus points, and actionable recommendations for decision-makers
  agent: {agent_name}

persona_consultation_task:
  description: >
    Provide expert consultation on: {consultation_topic}
    
    Background Context: {background_info}
    Specific Questions: {specific_questions}
    
    Draw upon your expertise to provide:
    1. Professional assessment of the situation
    2. Key considerations and potential impacts
    3. Recommended approaches or solutions
    4. Potential risks or challenges to consider
    5. Success metrics or evaluation criteria
    
    Tailor your response to be actionable and aligned with your professional expertise.
  expected_output: >
    Expert consultation response with professional insights, practical
    recommendations, and clear rationale based on your area of expertise
  agent: {agent_name}

comparative_analysis_task:
  description: >
    Compare and contrast multiple options or approaches: {comparison_topic}
    
    Options to analyze: {options_list}
    Evaluation criteria: {criteria}
    
    Provide a comparative analysis that includes:
    1. Strengths and weaknesses of each option
    2. How each aligns with your professional priorities
    3. Potential risks and benefits from your perspective
    4. Your recommendation with supporting rationale
    5. Implementation considerations for your preferred approach
    
    Use your professional judgment to provide objective, insightful analysis.
  expected_output: >
    A structured comparative analysis with clear evaluation of options,
    professional recommendations, and supporting rationale
  agent: {agent_name} 