# Task configurations for MeshAI CrewAI Backend
# These tasks support different types of agent interactions

initial_reaction_task:
  description: >
    Hey, what's your take on this: {topic}
    
    Just give me your honest first reaction - what comes to mind from your perspective?
    Keep it natural and conversational, like you're chatting with colleagues.
    Give me just 1-2 sentences max.
    
    Context: {context}
  expected_output: >
    A natural, conversational response in 1-2 sentences sharing your immediate thoughts
  agent: {agent_name}

group_discussion_task:
  description: >
    We're having a discussion about: {topic}
    
    Here's what others have said so far:
    {other_reactions}
    
    What do you think? Feel free to react to what others said, share your perspective, 
    ask questions, or agree/disagree. Keep it to 1-2 sentences - just like a natural conversation.
    
    Round: {round_number}
  expected_output: >
    A natural conversational response in 1-2 sentences that engages with the discussion
  agent: {agent_name}

focus_group_initial_task:
  description: >
    We're doing a focus group about: {campaign_description}
    
    Our goals for this session: {session_goals}
    
    What's your initial reaction? Just talk through your thoughts in 2-3 sentences - 
    what stands out to you? Any concerns or opportunities you see?
    What does this mean from your professional angle?
    
    Think of this like you're sitting around a table with other professionals
    sharing your honest opinion. Keep it conversational and concise.
  expected_output: >
    A conversational response in 2-3 sentences sharing your professional perspective
    naturally, like speaking in a focus group
  agent: {agent_name}

focus_group_discussion_task:
  description: >
    We're continuing our discussion about: {campaign_description}
    
    Here's what people have been saying recently:
    {recent_context}
    
    What are your thoughts on what's been shared? Anything you want to add,
    question, or build on? Keep it to 1-2 sentences like a natural conversation.
    
    This is round {round_number} - let's keep the conversation flowing naturally.
  expected_output: >
    A conversational contribution in 1-2 sentences that builds on the discussion naturally
  agent: {agent_name}

campaign_analysis_task:
  description: >
    We need your detailed thoughts on this campaign: {campaign_description}
    
    Goals we're looking at: {analysis_goals}
    
    Walk me through what you're thinking - what works, what doesn't?
    What would you be worried about? What opportunities do you see?
    
    This needs more detail since it's analysis, so give me 3-4 key points
    but keep each point conversational like you're explaining to a colleague.
  expected_output: >
    A conversational analysis covering 3-4 key points naturally,
    like explaining your detailed thoughts to a colleague
  agent: {agent_name}

summary_synthesis_task:
  description: >
    We just finished discussing: {topic}
    
    Here's everything that was covered:
    {full_discussion_context}
    
    Can you help summarize what came out of this conversation?
    What were the main points? Where did people agree or disagree?
    What should we take away from this discussion?
    
    Give me the key takeaways in 3-4 sentences like you're wrapping up a meeting.
  expected_output: >
    A conversational summary in 3-4 sentences that captures the key discussion points
    and takeaways in a natural, meeting-wrap-up style
  agent: {agent_name}

persona_consultation_task:
  description: >
    I need your advice on: {consultation_topic}
    
    Background: {background_info}
    Specific questions: {specific_questions}
    
    What do you think? What would you recommend based on your experience?
    Keep it to 2-3 sentences - just your honest professional opinion.
  expected_output: >
    Conversational advice in 2-3 sentences based on your expertise,
    shared naturally like giving quick professional advice
  agent: {agent_name}

comparative_analysis_task:
  description: >
    I'm trying to decide between these options: {comparison_topic}
    
    Options: {options_list}
    Looking at: {criteria}
    
    What's your take? Which way would you lean and why?
    Give me 2-3 sentences with your perspective and reasoning.
  expected_output: >
    A conversational comparison in 2-3 sentences sharing your perspective
    and recommendation naturally
  agent: {agent_name} 